import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'building_class.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'building_class.g.dart';

@freezed
abstract class Building with _$Building {
  const factory Building({
    @Default('-') String name,
    @Default(false) bool isFavorite,
  }) = _Building;

  factory Building.fromJson(Map<String, Object?> json) =>
      _$BuildingFromJson(json);
}
