import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'device_type_class.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'device_type_class.g.dart';

@freezed
abstract class DeviceType with _$DeviceType {
  const factory DeviceType({
    @Default('-') String name,
    @Default('-') String descripton,
  }) = _DeviceType;

  factory DeviceType.fromJson(Map<String, Object?> json) =>
      _$DeviceTypeFromJson(json);

}
