import 'package:freezed_annotation/freezed_annotation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'floor_class.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'floor_class.g.dart';

@freezed
abstract class Floor with _$Floor {
  const factory Floor({
    @Default('-') String name,
  }) = _Floor;

  factory Floor.fromJson(Map<String, Object?> json) => _$FloorFromJson(json);
}
