import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'smart_device_class.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'smart_device_class.g.dart';

@freezed
abstract class SmartDevice with _$SmartDevice {
  const factory SmartDevice({
    @Default('-') String qrCode,
    @Default('-') String deviceType,
    @Default('-') String smartKey,
    @Default('-') String sgtin,
    @Default('-') String name,
    @Default('-') String description,
    @Default('-') String room,
    @Default('-') String floor,
    @Default('-') String building,
    int? sembastKey,
  }) = _SmartDevice;

  factory SmartDevice.fromJson(Map<String, Object?> json) =>
      _$SmartDeviceFromJson(json);

// Map<String, dynamic> toMap() => {
//         'qrCode': qrCode,
//         'deviceType': deviceType,
//         'smartKey': smartKey,
//         'sgtin': sgtin,
//         'name': name,
//         'description': description,
//         'room': room,
//         'floor': floor,
//         'building': building,
//       };
}


